last: 5
images:
  k8s.gcr.io:
    - etcd
    - pause
    - kube-proxy
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - coredns/coredns
    - metrics-server/metrics-server
    - ingress-nginx/controller
    - ingress-nginx/controller-chroot
    - ingress-nginx/kube-webhook-certgen
    - kube-state-metrics/kube-state-metrics
